# Generated by Django 5.0.2 on 2024-03-12 22:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('average_rating', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('Veg', 'Vegetarian'), ('NonVeg', 'Non-Vegetarian')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=240, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=50)),
                ('toppings', models.TextField()),
                ('food_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='app.foodproduct')),
            ],
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='fvrt_by',
            field=models.ManyToManyField(blank=True, null=True, to='app.user'),
        ),
    ]
