# Generated by Django 5.0.2 on 2024-03-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_foodproduct_fvrt_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='fvrt_by',
            field=models.ManyToManyField(blank=True, null=True, to='app.user'),
        ),
    ]
