# Generated by Django 5.0.2 on 2024-03-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_city_user_city_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='city_name',
            new_name='city',
        ),
    ]
