# Generated by Django 5.0.2 on 2024-03-13 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_city_name_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='fvrt_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
